### ISSUE TITLE
Suggested quiz questions

### ISSUE THREAD

**Issue by MarcoAJanssen** [virtualcommons/port-of-mars#120]
When does the game ends?
-	After an unknown number of rounds
-	When Upkeep reaches zero
-	After an unknown number of rounds, or earlier if Upkeep reaches 0
-	When one of the players reaches 20 points
Can you chat with other participants?
-	No, communication is not possible in this game.
-	Yes, in the chat box during the whole duration of the game.
-	Yes, in the chat box during designated periods.
-	Yes, if Upkeep is bigger than 35.
How do you trade cards with others?
-	During the trade period you indicate your preferences of cards
-	Expressing your preferences in the chat box is sufficient.
-	Discuss via chat and then express your deals during trade period
-	When you allocate your time-blocks.
If Upkeep drops below 65 and is above 35 what happens?
-	Chat is not possible anymore.
-	Two events will happen that round.
-	You get an additional four time-blocks.
-	You get an extra accomplishment card.
The following card is an example of an accomplishment card [image]. What do we see on this card?
-	It costs x influence cards, y influence cards , and ..
-	You earn x points
-	You can only buy this card if you have the required influence cards
-	All above three answers are correct
The following card is a special accomplishment card [image screwcard]. What does this card do?
-	It cost the player nothing individually
-	The Upkeep level of the group will be reduced with x points
-	The individual player will earn x points
-	All above three answers are correct
You get each round 10 time blocks? Which of the following statements is incorrect:
-	You can spend as many time blocks as you want.
-	Every time block not spend can be saved for next round.
-	Each player has their special skills impacting the costs of influence cards.
-	By default each time-block in Upkeep increases the Upkeep of the group with one unit.
If Upkeep drops below 35 which of the following statements is true?
-	The game ends
-	The group will experience three events this round.
-	The player with the least amount of points is eliminated.
-	Nothing, life as usual on Mars.
At the start of each round, 25 units is subtracted from Upkeep. What does this represent?
-	The lack of contributions of others.
-	A standard wear and tear.
-	Solar flares
-	The costs of trade.

**Comment by alee** [comment]
The quiz has been implemented and I assume the questions are acceptable - reopen if needed.
