### ISSUE TITLE
post game survey

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#121]
collect demographic data + other metrics
lgbtq+ inclusive language

**Comment by alee** [comment]
We could also redirect to Qualtrics and pass along an anonymized participant ID to be ingested as [embedded data](https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/embedded-data/). This would let the researchers build their own survey and 
be less work for us besides figuring out how to route them to the exit survey after the end of the game

That said I suspect if we put the survey in the game interface there is a greater chance they actually fill it out than if we redirect them to some qualtrics site to take an exit survey.. not sure about that though.

**Comment by alee** [comment]
surveys have been implemented in Qualtrics, still need to wire up completion endpoints in #360
