### ISSUE TITLE
comments tutorial

### ISSUE THREAD

**Issue by MarcoAJanssen** [virtualcommons/port-of-mars#164]
Hereby some suggested improvements:

"The game progresses in rounds. There is an indefinite number of rounds per game. Therefore, the game can end at any time given that Upkeep does not decline to zero."
This should be "at any time even if Upkeep does not decline to zero".

"Each phase has a time limit of 5 minutes." This would be way to long. This could lead a round to last 25 minutes. 2 minutes seems more appropriate.

This text block does not respond when Iclick Next. And why do I get the message that curator wants to trade if I still have to make an investment. The textblock blocks my access to Upkeep investment. I am confused at this stage what the tutorial aims to do. I had expected you walk through one complete round.

**Comment by lfaivre** [comment]
@MarcoAJanssen 
@Nick42791 

The tutorial is working now. We may need to address the wording of some of the elements and quiz questions, but the functionality is fully implemented at this point.
