### ISSUE TITLE
Suggested UI changes for usability and accessibility

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#167]
![1 INVESTMENTS](https://user-images.githubusercontent.com/8737685/72941298-d7b4e280-3d2d-11ea-884a-b700075b5139.png)

![2 TRADE](https://user-images.githubusercontent.com/8737685/72941306-daafd300-3d2d-11ea-95d2-4f89cae87aff.png)

![3 PURCHASE](https://user-images.githubusercontent.com/8737685/72941310-de435a00-3d2d-11ea-9262-e4d3fa69eca0.png)

via Michal

**Comment by chrstngyn** [comment]
@Nick42791 @lfaivre

**Comment by alee** [comment]
I think most of these have been obsoleted, please reopen with new
