### ISSUE TITLE
find a more intuitive name for "upkeep"

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#168]
During our usability UI/UX consult with William we discussed changing the `upkeep` term to help participants better connect to the group public good they're trying to maintain as `upkeep` felt too abstract.

possible replacements:

- community health
- community resources
- infrastructure health
- base health
- settlement health
- something something index

**Comment by chrstngyn** [comment]
- community hp
- society health
- nation/state/commonwealth hp
- society welfare

**Comment by alee** [comment]
I think we've settled on `system health` but will wait to hear back for confirmation from the rest of the group on Slack

**Comment by alee** [comment]
using `system health` for now, closing
