### ISSUE TITLE
complete PersonalGain mars event handling

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#196]

**Comment by chrstngyn** [comment]
- [ ] create new mars log message
- [ ] create better indicator to notify that player has locked in their vote

do we allow players to change their vote or just lock in the first button they click?

**Comment by cpritcha** [comment]
> do we allow players to change their vote or just lock in the first button they click?

allowing them to change their vote until the time limit or everyone has finished is simpler (doesn't require locking on the server and letting the client know that they have voted and can't vote again).

how indecisive people may also be useful for analysis later

**Comment by cpritcha** [comment]
could ask on slack too to see what everyone thinks

**Comment by chrstngyn** [comment]
sounds good, will do

**Comment by chrstngyn** [comment]
done
