### ISSUE TITLE
add default "bot" behavior

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#234]
define some baseline bot behavior that can take the place of a disconnected client in a game

issues to deal with:

1. investment strategy
2. trade behavior (deny all trades?)
3. purchase accomplishments / discards
4. chat like Eliza? (https://github.com/JStumpp/awesome-chatbots) - probably one to punt on

**Comment by chrstngyn** [comment]
- [ ] generate specialty influence only
- [ ] only accept trades in 1:1 trades

**Comment by chrstngyn** [comment]
resolved by various commits: https://github.com/virtualcommons/port-of-mars/commits/master/server/src/rooms/game/state/bot.ts

#535 addresses improving current bot behavior
