### ISSUE TITLE
show vote totals in mars log (events)

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#283]
vote results in the mars log should always show how many votes particular players were given

**Comment by lfaivre** [comment]
From #295 

> Voting events: do not display who voted for what, but display what got voted on (Personal Gain: 2 players voted yes, 12 system health was destroyed, hero or pariah, Roles X Y Z each received A B C votes, Compulsive Philanthropy)

**Comment by chrstngyn** [comment]
duplicate #272
