### ISSUE TITLE
apostrophes on card text not displaying properly

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#285]

**Comment by cpritcha** [comment]
doesn't seem to occur in development

**Comment by lfaivre** [comment]
i thought this was an issue with character encoding ([link](https://stackoverflow.com/questions/4086717/why-do-symbols-like-apostrophes-and-hyphens-get-replaced-with-black-diamonds-on), [link](https://discussions.apple.com/thread/6322119)), but i found a rogue question mark symbol in the data which is likely the issue. the pr will close this, and we can reopen if this isn't the issue
