### ISSUE TITLE
3/2 playtest notes

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#295]
- [ ] increase contrast (for chat and other elements), hard to read. this may be mitigated by new palette changes from 
- [ ] trading: is hard to see the "Send Trade" button at the bottom. Perhaps we can incorporate the "Send Trade" functionality into the top "Request Trade" 
- [ ] easily forget to click "Done"
- [x] continue to rename "upkeep" to system health in all events
- [ ] Voting events: do not display who voted for what, but display what got voted on (Personal Gain: 2 players voted yes, 12 system health was destroyed, hero or pariah, Roles X Y Z each received A B C votes, Compulsive Philanthropy)
- [ ] disabled iconography is too difficult to see, hard to tell what is needed. Instead we need to come up with a way to highlight what you have and distinguish it from what you still need
- [ ] trades you own should have "Cancel", not "Decline"
- [ ] discard phase: accomplishment cards in the bottom center was a little wonky, seems to be almost cut off but not quite
- [ ] when making investment contributions it would be nice to add the amount contributed in the same place / visual field

**Comment by lfaivre** [comment]
for the disabled iconography, i think we can add a background color or border for the elements that the user has instead of the opacity modifier. i'll send in a pr and see what y'all think

**Comment by lfaivre** [comment]
![Screen Shot 2020-03-04 at 11 19 00 AM](https://user-images.githubusercontent.com/43051098/75909793-fa94e500-5e09-11ea-9a2e-39c2595914f4.png)

^ something like this

**Comment by lfaivre** [comment]
> discard phase: accomplishment cards in the bottom center was a little wonky, seems to be almost cut off but not quite

@alee could you give me some more context/clarity on this? it sounds like an easy fix, but not entirely sure if it's an issue with the scrollable div or with the card formatting

**Comment by lfaivre** [comment]
> Voting events: do not display who voted for what, but display what got voted on (Personal Gain: 2 players voted yes, 12 system health was destroyed, hero or pariah, Roles X Y Z each received A B C votes, Compulsive Philanthropy)

being handled with #283

**Comment by lfaivre** [comment]
Created two separate issues to handle the leftover playtest notes: #316, #317
