### ISSUE TITLE
tutorial: trade issue

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#306]
It's possible to send the trade before the tutorial steps regarding trading are done. This is problematic since the send trade button disappears when you issue the trade for that person, making it seem like you can't move forward in the tutorial

Not sure what the right way to fix this is that doesn't overcomplicate things. Would it be possible to make the tutorial smarter and able to detect if a trade is pending and move forward?

**Comment by Nick42791** [comment]
Closed in #305
