### ISSUE TITLE
Surveys that need to be included before and after game

### ISSUE THREAD

**Issue by MarcoAJanssen** [virtualcommons/port-of-mars#312]
![image](https://user-images.githubusercontent.com/22354826/76021749-0dc7b380-5ee3-11ea-9d74-18e405b2f6eb.png)

**Comment by alee** [comment]
Thanks @MarcoAJanssen - do the participants in rounds 2 and later have to do the same exit survey that they did in round 1?

**Comment by alee** [comment]
also, could you please enter the qualtrics survey URLs as text, not as a PNG? Otherwise we run the risk of copy/paste errors :sweat_smile:

**Comment by alee** [comment]
add survey redirect at the end of each survey with embedded data: https://www.qualtrics.com/support/survey-platform/survey-module/survey-flow/standard-elements/passing-information-through-query-strings/

**Comment by chrstngyn** [comment]
record that a user has taken a survey and redirect them back to game after they take survey

**Comment by alee** [comment]
surveys have been added, but we need to test data collection on the Qualtrics end and the redirect back to the port of mars app.

each subsequent tournament round will need

**Comment by MarcoAJanssen** [comment]
OK, I will create 8 survey links

**Comment by alee** [comment]
No need to create all of them now @MarcoAJanssen but it might be good to have it for rounds 2 and 3 at least so we can test those out too. Actually, will the survey questions be different in each round?

 If not, we will be able to uniquely identify which round the survey was taken on with the new embedded data we are passing into the survey (as well as the participant of course)

**Comment by MarcoAJanssen** [comment]
Rounds 2 and later are the same. Here the links
Beginning of round 1: https://asu.co1.qualtrics.com/jfe/form/SV_0c8tCMZkAUh4V8x
End of round 1: https://asu.co1.qualtrics.com/jfe/form/SV_6FNhPbsBuybTjEN

Beginning of round 2: https://asu.co1.qualtrics.com/jfe/form/SV_9N65NiZ7uJjxEIl
End of round 2: https://asu.co1.qualtrics.com/jfe/form/SV_3CPgFldYfflph53

Beginning of round 3: https://asu.co1.qualtrics.com/jfe/form/SV_0q6U0vQb0C5akjX
End of round 3: https://asu.co1.qualtrics.com/jfe/form/SV_6sTU61E51o7jmsJ

Beginning of round 4: https://asu.co1.qualtrics.com/jfe/form/SV_0IE7wcxlBY1gvDD
End of round 4:https://asu.co1.qualtrics.com/jfe/form/SV_ePaLp1ZEp97LNJz
