### ISSUE TITLE
add player dashboard

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#319]
# Player Dashboard Requirements

Create an participant account edit page.

## New Player

Onboarding action items that the player needs to be complete: 

1. accept IRB consent form
2. register and verify email address
3. take tutorial and pass quiz

### Eligible to participate in an upcoming game

- take intro survey
- show schedule of upcoming games

### Already participated

- exit survey 
- stats for previously played games
- display info for next tournament round
- track tournament completed state 

### Ineligible player
- track state to determine if player is eligible to play another game
- display stats from previous games
- textual info to explain why player is ineligible to play another game

**Comment by lfaivre** [comment]
[figma mockup](https://github.com/virtualcommons/port-of-mars/issues/319)

**Comment by alee** [comment]
Thanks @lfaivre! This looks like a good start but would probably benefit from some more graphics / images, it's a little text heavy at the moment, no need to embed the actual images, just placeholders. 

Other comments:

I think we should get rid of the Onboarding section and make that whole column your stats or something along those lines. I think we can just have Surveys listed in the Action Items section if they need to be done. There's a dependency on the steps that can be done:

1. Agree to / sign the consent form
2. validate email address
3. take the intro survey (probably no need to call it intro survey)
4. go through the tutorial
5. at this point they can participate in a game
6. after participating in a game, offer an (optional) exit survey
7. if eligible for the next round of games, they have to take another intro survey before being eligible to participate in that game (should confirm if this is true with @MarcoAJanssen)
8. after participating in that game, offer an (optional) exit survey

Steps 7/8 repeat until the tournament is over.

We also need messaging informing them what the status of the tournament is, which round the tournament is on, whether or not they are eligible for participating in the current round (or subsequent rounds), so we need room for some descriptive paragraph.

**Comment by lfaivre** [comment]
notes from stand-up meeting:

- move consent form to separate page (?)
- move intro survey to tutorial (?)
- tutorial is always available in dashboard
- add general tournament information to stats section
- add to calendar link for upcoming games
- create service to handle a user's next actions
