### ISSUE TITLE
3/11 pretest issues

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#328]
This was running an old build (8eebb1a113fd54fcbc254507659dbc45d122b3a8) so some of these may have been fixed already.

- [x] tutorial progression didn't work for anyone other than the Researcher
- [x] researcher and politician were unable to trade, the resource button got grayed out. A refresh fixed it so perhaps we need some instructions on if people run into some common issues. Perhaps we can include some common fixes next to the "Report a Problem" link
- [ ] Compulsive Philanthropy should probably show the vote totals?
- [x] total upkeep contributions should be listed in the Mars Log
- [ ] upkeep calculations do not appear to be correct during the sandstorm, we have to start verifying this
- [x] a trade from the tutorial seems to have persisted into the actual game (Researcher)
- [x] add an explicit step in the tutorial to highlight the "Done" button.
- [ ] tutorial - increase contrast of the instructions to highlight what needs to be done (maybe use white instead of black?)

**Comment by chrstngyn** [comment]
done button is highlighted during tutorial, but they aren't required to click on it to progress to the next step.

**Comment by chrstngyn** [comment]
compulsive philanthropy shows vote totals for the winner. should it show vote totals for other players?

**Comment by alee** [comment]
closing in favor of separate issues

upkeep calculations: #324 and #339 

I'm not sure about the compulsive philanthropy actually, I assume it's an open vote but we probably need to check with the rest of the team on that.

tutorial contrast improvements might be folded in with other incoming UI changes
