### ISSUE TITLE
add basic website info to pages

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#334]
On every page besides the full game interface it'd be useful to have:

- build ID from `git describe --tags`
- acknowledgements (funding from II, NSF, etc.)
- copyright
- license info
- link to github?

**Comment by chrstngyn** [comment]
can you give more details on acknowledgements that need to be included?

i added a footer at the bottom of the application. the footer can be toggled via button click to reveal more space to include more information that can be included in the footer

**Comment by alee** [comment]
How about Compute Canada, GBCI, and the ASU Interplanetary Initiative for now.. Fingers crossed we'll be able to add NSF and a few more names to the list later 😅

**Comment by chrstngyn** [comment]
- [ ] make the footer responsive to narrower screen resolutions, text gets truncated at the moment

**Comment by chrstngyn** [comment]
resolved in 1139b2303956dc212e5994cef2b888b74a454d5d. closing for now; we could reopen in the case that other things need to be added or changed
