### ISSUE TITLE
Game loop state change processing

### ISSUE THREAD

**Issue by Nick42791** [virtualcommons/port-of-mars#338]
Currently, the game loop does not allow for us to look at all of the state changes that happened in a round and evaluate where the game should go based off those changes.

The current workaround is to call EnteredDefeatPhase() at the end of all phases, and check to see if we should enter the defeat phase.

To fix, we have both an Entered Phase and an Exited Phase. By doing this, we could look at all of the changes that finalize methods might create and move based off those.

**Comment by alee** [comment]
this has been mostly resolved by @cpritcha , reopen to refactor as needed
