### ISSUE TITLE
reconnect to existing

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#340]
How do I reconnect to an existing game instance in colyseus? I was hoping that since the roomId is stored in the database I could use use roomId to reconnect to the game by creating a new reservation for the player.

For posterity here is what I've tried

```typescript
gameRouter.get('/latest/active', async (req: Request, res: Response, next: NextFunction) => {
  try {
    if (!req.user) {
      next(Error('no user'));
      return;
    }
    const roomId = await getLatestActiveGameByUserId((req.user as any).id);
    logger.info('connecting to room', {roomId});

    if (!roomId) {
      res.json({
        error: 'no active game found'
      });
      return;
    }

    const reservation = matchMaker.joinById(roomId);
    logger.info('reservation:', reservation);
    res.json(reservation);
  } catch (e) {
    next(e);
  }
});
```

but that doesn't seem to work because in the logs I get something like

```
server_1  | {"level":30,"time":1584038030664,"pid":95,"hostname":"dd6a34a2879f","msg":"connecting to room {\"roomId\":\"rXUO2h3F6\"}","v":1}
server_1  | {"level":30,"time":1584038030665,"pid":95,"hostname":"dd6a34a2879f","msg":"reservation: {}","v":1}
server_1  | {"level":30,"time":1584038038666,"pid":95,"hostname":"dd6a34a2879f","msg":"Disposing of room rXUO2h3F6","v":1}
```

The reservation turned back is empty. The dispose method on the room is also called on a different room that doesn't seem to do anything but is created when at the same time as the game I want to connect to. I have two players playing through the game separate firefox containers so the game isn't getting disposed when I try to refresh one container tab.

How should I be reconnecting to an existing game instance? Using `client.reconnect` instead?

Full code at https://github.com/virtualcommons/port-of-mars/tree/question-340

@endel

**Comment by cpritcha** [comment]
Looking at https://github.com/colyseus/colyseus/blob/c4a192d749f0a2f63dcb6424729f6c7ba6abe2c1/src/MatchMaker.ts#L97 it looks I need a sessionId too. I'll try quickly using local storage in the browser and I'll see if that works.

**Comment by alee** [comment]
https://docs.colyseus.io/server/room/#allowreconnection-client-seconds

https://docs.colyseus.io/client/client/#reconnect-roomid-string-sessionid-string

**Comment by cpritcha** [comment]
Adding allowReconnect to the onLeave method resulted in a working reconnection.

**Comment by cpritcha** [comment]
Looking at https://github.com/colyseus/colyseus/blob/c4a192d749f0a2f63dcb6424729f6c7ba6abe2c1/src/MatchMaker.ts#L97 it looks I need a sessionId too. I'll try quickly using local storage in the browser and I'll see if that works.
