### ISSUE TITLE
3/12 pretest issues

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#346]
- [x] trade from previous round still had selected information (e.g., selected curator the previous round, next round curator was still selected)
- [x] received 2 events at exactly 65 upkeep. It should be 35 <= upkeep < 65 and 3 events at < 35
- [ ] allow for altruistic trades (0 for X>1 or X>1 for 0, but no 0 for 0)
- [x] in general, the UI is too small and we might need to think of a major redo that maximizes the layout for the action you want to take when you select it #351 
- [ ] tutorial flow should have the player click "Done" to terminate every phase to highlight the habit of clicking Done after completing an action
- [ ] final mars log should be in reverse descending order (most recent first, oldest last)
- [ ] vote log events should be set the category to the event type that generated the vote
- [x] mars log system health modifications need to be finer grained: `standard wear and tear reduced system health by 25. Your group invested a total of Y into system health last round. Event Y reduced system health by Z.`

**Comment by Nick42791** [comment]
#347 fixes the trade from previous round info

**Comment by chrstngyn** [comment]
issue #167

**Comment by alee** [comment]
this might be an iPad / safari only issue but this showed up after the Audit event was in effect:

![IMG_0310](https://user-images.githubusercontent.com/22534/76568460-1d5c7480-646e-11ea-8e8f-947126eeb519.PNG)

**Comment by chrstngyn** [comment]
commit d9295cc resolve mars log system health msgs

**Comment by chrstngyn** [comment]
action items moved to #374 to consolidate play test tasks
