### ISSUE TITLE
improve mars log messages

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#350]
- support markdown messages
- add json payload
- make category more useful by making it an enum or ADT

**Comment by chrstngyn** [comment]
created categories for mars log messages in pr #349

**Comment by chrstngyn** [comment]
@alee @cpritcha thoughts on this https://marked.js.org/#/README.md ?

**Comment by cpritcha** [comment]
Looks good to me. It seems like like it's one of the more popular markdown to html converters.

**Comment by alee** [comment]
LGTM! I think we can bypass output sanitization since we are generating the output, are there any user generated things that go into these MarsLogMessages?

**Comment by chrstngyn** [comment]
user generated activities include:
- any trade request activity that includes sent, accepted, rejected or cancelled trades
- purchasing accomplishments

am i missing anything?

**Comment by alee** [comment]
Yep those should all be fine, I'm more concerned with user generated content, so if they can enter maliciously handcrafted script strings that get interpreted by the page. I don't think there's any user-entered content in these messages so they should be fine (we should be sanitizing their chat messages but I *think* that's being take care of since we tested that out?)

**Comment by chrstngyn** [comment]
oh i misunderstood. thanks for the clarification!

no, i don't believe there's any user-entered content that gets logged. only:
- user votes, trade and purchase actions
- events
- system health increase/decrease/contributions

**Comment by chrstngyn** [comment]
- [ ] partition and organize logs into rounds
- [ ] refactor mars log color generation -> dictionary that maps log category to color
