### ISSUE TITLE
consider reorganizing UI flow

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#351]
Overall, we have something like an aircraft instrument panel that's too complicated, has too many things, and as a result all font sizes are too small and hard to see on smaller screens. We probably need to drastically rethink the UI so that for a given Phase and set of available Actions those activities are maximized in the center, with all the other informational content available to be maximized. 

Right now we are having players perform actions within tiny containers that drastically affects usability of the app (e.g., trade).

We should also adopt a CSS framework and use their standard grid classes etc. either bootstrap 4 or tailwind. bootstrap 4 is likely less work since we're already using it in some of our Vue components (?)

**Comment by alee** [comment]
maybe the first low hanging fruit is to redo the trading component and convert the left & right sidebars to drawers

**Comment by chrstngyn** [comment]
https://www.figma.com/file/wVu7L9qZzVWzwR7cbmvsDA/Port-of-Mars-Rework?node-id=0%3A1

**Comment by chrstngyn** [comment]
meeting notes 3/18

**lorenzo**
- [ ] ui board measurements/dimensions
- [ ] base gameboard

**nick**
- [ ] modals

**christine**
- [ ] event view
- [ ] status page
- [ ] ask marco about chat and system health bar and chat

**Comment by alee** [comment]
this is mostly done, future refinement happening in separate issues
