### ISSUE TITLE
record time remaining in phase for each event

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#356]
currently only recording time stamps of events.

might be better to record time since last event instead.

**Comment by alee** [comment]
I know you've already implemented this but I'd suggest refactoring this so you set it in `Event.apply(GameState)` instead of threading `game.state.timeRemaining` into the instantiation of every event.

In GameEventWithData you can template method out the `apply` so that it automatically sets its own `timeRemaining` to `GameState.timeRemaining` before doing its own custom `apply` stuff.

**Comment by cpritcha** [comment]
We need `timeRemaining` for saving the event in the DB. Some the logic for passing in the timeRemaining to the event could be put in a command superclass though.

**Comment by cpritcha** [comment]
`timeRemaining` is constantly changing so it needs to be recorded when the event is created otherwise the `timeRemaining` value in the db may not be the true `timeRemaining` value

**Comment by alee** [comment]
I think you misunderstand. Set `this.timeRemaining = state.timeRemaining` in `Event.apply(GameState)`

**Comment by cpritcha** [comment]
I agree that there's a lot of duplication in threading through the `timeRemaining`. 

I think it would cleaner to transform the events so that they have a timeRemaining before they are sent to the persister.

In the game room from

```typescript
  onMessage(client: Client, message: Requests) {
    const cmd = this.prepareRequest(message, client);
    const events = cmd.execute();
    this.state.applyMany(events);
    this.persister.applyMany(this.gameId, events);
  }
```

to

```typescript
  onMessage(client: Client, message: Requests) {
    const cmd = this.prepareRequest(message, client);
    const events = cmd.execute();
    this.state.applyMany(events);
    const timeRemainingAnnotatedEvents = events.map(annotateTimeRemaing);
    this.persister.applyMany(this.gameId, timeRemainingAnnotatedEvents);
  }
```

**Comment by cpritcha** [comment]
I could also move out dateCreated from the object and annotate it after the events are applied.

**Comment by alee** [comment]
current implementation looks much improved to me so I think this can be closed now? (though I still think `persister.applyMany` should be `persister.save` :eyes: )
