### ISSUE TITLE
client side auth checks in router.ts

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#363]
Our routes are properly marked up using [requiresAuth router meta fields](https://router.vuejs.org/guide/advanced/meta.html) but we don't have any guards in place to prevent access to a page that `requiresAuth: true` in `client/src/router.ts`

Example from the router docs:

```
router.beforeEach((to, from, next) => {
  if (to.matched.some(record => record.meta.requiresAuth)) {
    // this route requires auth, check if logged in
    // if not, redirect to login page.
    if (!auth.loggedIn()) {
      next({
        path: '/login',
        query: { redirect: to.fullPath }
      })
    } else {
      next()
    }
  } else {
    next() // make sure to always call next()!
  }
})
```

The missing magical part is the `auth.loggedIn` check - since we're no longer using JWTs I assume we'll need to access the session cookie instead? @cpritcha 

Other resources:

https://blog.sqreen.com/authentication-best-practices-vue/

**Comment by cpritcha** [comment]
Since we're using a http-only cookie in production I don't think we can tell if it exists consistently (there's a hack that works in Chrome but not Firefox https://stackoverflow.com/questions/9353630/check-if-httponly-cookie-exists-in-javascript).

I think we should just redirect to login if we get a 401 response from the server.

**Comment by alee** [comment]
I'm open to that if it's a less invasive change. It's unclear how you return a 401 when the only request that is being made is to join a Colyseus room - do you have ideas on how to do that?

@endel @cpritcha

**Comment by alee** [comment]
Just as a footnote, at the moment it seems simpler to me to perform auth checks in the vue router which I guess would come at the expense of also setting a JWT token in client local storage after CAS authentication and using that JWT for client-side auth checks..

**Comment by cpritcha** [comment]
Turning the cookie to be not http only would also allow you to check in vue-router. Since you can see both in js in the browser I don't see any benefit to adding a jwt as well.

**Comment by alee** [comment]
disabling HttpOnly is a significant security vulnerability especially for a login token. I doubt we'll go that route, other than for extreme expedience

**Comment by alee** [comment]
this is mostly being handled in #443
