### ISSUE TITLE
Mars Events Persisting

### ISSUE THREAD

**Issue by Nick42791** [virtualcommons/port-of-mars#369]
The mars events array is not getting reset between rounds, or even between games. I have tried clearing my localstorage, restarting the server, removing the redis container, and resetting the db to no avail.

**Comment by alee** [comment]
this is probably related to the createPersistedState that's caching the vuex store in local storage. I'm surprised clearing localstorage didn't fix it though..

Try taking down the entire container stack:

1. `docker-compose down -v`
2. clear local storage in your browser
3. `docker-compose up --build -d`

**Comment by alee** [comment]
should be resolved by removing vuex-persister though we still need to solve #377
