### ISSUE TITLE
apply onJoin full state sync after reconnect

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#377]
Hi @endel! After successful reconnection (again to support transparent refresh) we would like to fully reinitialize our client state. Reconnection doesn't trigger the `onJoin` method but we would like to benefit from the full state synchronization that happens in [onJoin](https://docs.colyseus.io/state/overview/). Is it possible to trigger the full state synchronization manually in our `onLeave`?

**Comment by endel** [comment]
Hi @alee, sorry I've missed the notification for this, I've just created a PR to hopefully fix this here https://github.com/virtualcommons/port-of-mars/pull/380
