### ISSUE TITLE
client side project file restructure

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#381]
modals associated with phase/top level component is nested in that folder

components

1. GameDashboardStatic
(1a) Modals 
(1b) Chat
2. GameDashboardMain
(2a) EventPhase
(2b) InvestmentPhase
(2c) TradePhase
(2d) PurchaseAccomplishmentPhase
(2e) DiscardAccomplishmentPhase
3. Tutorial

**Comment by lfaivre** [comment]
i'm liking this setup, one change i'd suggest: i think `GameDashboardMain` should be renamed something like `GameDashboardPhases` or `GameDashboardDynamic` since they're a little more semantic than with the `Main` suffix. thoughts?

**Comment by lfaivre** [comment]
also, we'll need to apply a similar folder structure to the stylesheets

**Comment by chrstngyn** [comment]
> i'm liking this setup, one change i'd suggest: i think `GameDashboardMain` should be renamed something like `GameDashboardPhases` or `GameDashboardDynamic` since they're a little more semantic than with the `Main` suffix. thoughts?

that works for me!
