### ISSUE TITLE
clearly indicate when a trade is accepted or rejected

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#406]

**Comment by alee** [comment]
should we keep the trade in the list and visually mark it as accepted / declined and then let the user clear it away (and/or do a setTimeout and clear it away after N seconds)?

**Comment by alee** [comment]
it's the autoremove that is too abrupt

**Comment by chrstngyn** [comment]
an alert modal would be helpful

**Comment by Nick42791** [comment]
closed by #431
