### ISSUE TITLE
event: entrepreneur out of commission doesn't allocate timeblocks correctly

### ISSUE THREAD

**Issue by Nick42791** [virtualcommons/port-of-mars#408]
Should've only received 3 timeblocks; got ten

**Comment by alee** [comment]
strangely, later on the pioneer and curator got this event and were correctly allocated 3 timeblocks..

**Comment by Nick42791** [comment]
@alee I wrote a test to check this out in #415  and all seems to be good...
maybe some sort of connection error caused this?

**Comment by alee** [comment]
great, thanks for the test! I guess the bad news is now we have no idea why Marco was allowed 10 timeblocks on the client side when he only was supposed to have 3. @cpritcha do you think you can inspect the data from that game to see what happened?

Do we have server-side guards to validate the effects of these events as well? I.e., if out of commission is in effect for the Entrepeneur and they submit investments that total 10 timeblocks, will it flag that and return an error?

**Comment by alee** [comment]
figured out the culprit, should be addressed when #476 is fixed
