### ISSUE TITLE
'x' button to close out modal cuts off at the bottom of the screen

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#417]
![image](https://user-images.githubusercontent.com/8737685/79498141-b0447d80-7fdd-11ea-880e-a64d6352174c.png)

it might be more intuitive to the player if it was in the top right corner instead of at the bottom

**Comment by Nick42791** [comment]
on smaller screens, the modals do not resize properly. I'm working on a fix.
