### ISSUE TITLE
questions for group during playtest

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#448]
- should group investments be displayed in the mars log right after they happen? **answer** only add the log at the end of the round. add a popup window notifying the user of game investment / system health update
- should each mars log message include the round number or should we just demarcate them (like in the final mars log)
- should we do wear & tear before applying group investment (and what happens if standard wear & tear brings system health <= 0 at that time - should we consider group investment + standard wear & tear as happening at the exact same time

**Comment by chrstngyn** [comment]
- create logs for inventory updates for a player after investment phase?

**Comment by chrstngyn** [comment]
>     * should group investments be displayed in the mars log right after they happen? **answer** only add the log at the end of the round. add a popup window notifying the user of game investment / system health update
> 
>     * should each mars log message include the round number or should we just demarcate them (like in the final mars log)
> 
>     * should we do wear & tear before applying group investment (and what happens if standard wear & tear brings system health <= 0 at that time - should we consider group investment + standard wear & tear as happening at the exact same time

see #350
