### ISSUE TITLE
ui is a square

### ISSUE THREAD

**Issue by Nick42791** [virtualcommons/port-of-mars#487]
It appears that for some reason, the ui is now a square, with bars on either side.
![squareView](https://user-images.githubusercontent.com/31869062/81120713-256ee880-8ee2-11ea-8385-57e94c68d550.png)

**Comment by lfaivre** [comment]
this is fixed in one of my newer commits. i was playing around with screen resolution support but forgot to revert to the old resolution (max/min height and width)

**Comment by Nick42791** [comment]
@lfaivre sounds good! If you wouldn't mind closing this issue when that commit is merged, that would be great.
