### ISSUE TITLE
trade filtering 

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#495]
Clicking on "Your Trades" or "All Active Trades" briefly brings up all your cancelled trades

**Comment by Nick42791** [comment]
yeah, that happens because the trade isn't actually deleted from anything, just hidden. will work on a fix now. Thanks!

**Comment by chrstngyn** [comment]
is it necessary keep cancelled trades in store- > tradeSet? @cpritcha @alee

**Comment by Nick42791** [comment]
@chrstngyn, it's not necessary, but a lot easier to have the client manage the asynchronous hiding than it is to have the server send a message to the client to hide a trade, then two seconds later, send another message to delete it.

The server does delete all the trades from the phase at the end of the phase, so it's not cluttered.
