### ISSUE TITLE
trade 0 for 0 resources should not be an allowed condition

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#505]
altruistic trades should only be 1-0 or 0-1
![image](https://user-images.githubusercontent.com/8737685/81983448-46bd8c00-95e8-11ea-8e01-cc421a152211.png)

**Comment by alee** [comment]
The `canPlayerMakeTrade` method in `shared/validation.ts` is supposed to prevent this I think but perhaps we should have an `isValidTrade` method to augment or replace the `canSendTradeRequest and `canPlayerMakeTrade` methods..
