### ISSUE TITLE
 when requesting trade from a bot, logs for invalid trades infinitely reproduce

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#506]
requested 1 resource from bot with 0 offered resource, `ADD_TO_MARS_LOG` gets called infinitely

![image](https://user-images.githubusercontent.com/8737685/81983880-e549ed00-95e8-11ea-9a42-03d8a5445343.png)

**Comment by chrstngyn** [comment]
also, when bot accepts a trade (e.g. request 1 resource, 0 offer) inventory of received resource doubles - e.g. request 1 science from researcher bot and your inventory gets updated to 2

**Comment by alee** [comment]
I think this has been resolved?
