### ISSUE TITLE
invalid / invalidated trades needs better messaging

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#511]
- [ ] all canceled trades should be explicitly listed in the mars log but listing insufficient resources as a reason gives TMI
- [x] invalid trade requests should be visually marked as invalid for the receiver with only the 'cancel' button available
- [x] verify that trades were being cancelled for good reason in the current pretest game (5/15 15:18)

**Comment by chrstngyn** [comment]
>     * [x]  invalid trade requests should be visually marked as invalid for the receiver with only the 'cancel' button available

resolved by 360601e663df8c633c8ffdf6a7d5fe31d3104f8c. accept button is disabled if player has insufficient resources to fulfill trade

**Comment by alee** [comment]
closing for now, can revisit later after initial round of feedback from the tournament
