### ISSUE TITLE
game events time stamps suspiciously identical

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#513]
Time recorded doesn't seem to match true time for one game.

Events coming in from the client also seem to get batched as well.

Evidence:

The entered-victory-phase event occurs at the exact same time as many other discard events. The time remaining all those events was the same (10000) indicating that the entered-victory-phase occurred first. Other events are seems to occur in batches corresponding to the event loop tick.

The other full game played has correct time stamps matching expectations where almost every event has its unique dateCreated value.

**Comment by alee** [comment]
I think this has been fixed now, but we should monitor future data dumps closely for regressions
