### ISSUE TITLE
tutorial improvements

### ISSUE THREAD

**Issue by connor4410** [virtualcommons/port-of-mars#514]
“Ready to advance” text in the tutorial should say “the phase will end” instead of “the round will end”

The tutorial doesn’t complete the trade that the player is instructed to request.  It may be helpful to show the trade notification animation (accepted/rejected) shown in the actual game instead of advancing before a decision is made by the trader.  

It may also be helpful to show the inventory resource quantities reflective of the purchases made in the buy stage of the tutorial and add an accomplishment that would be purchasable with those resources rather than the current system that gives the player ten of each resource and a random accomplishment.  Additionally, the player’s score doesn’t change after purchasing the accomplishment, another discrepancy that could cause confusion.

**Comment by alee** [comment]
These should have been addressed by now. Thanks for the report @connor4410 !
