### ISSUE TITLE
In-Game Issues- Bots and Countdown Timer

### ISSUE THREAD

**Issue by connor4410** [virtualcommons/port-of-mars#516]
Phase countdown timer working incorrectly.  Appears to be flashing between multiple timers.  Phases are ending early when the timer with less time hits 00:00.  Each phase end is saving the previous timer and advancing the phase when the earliest to be started hits 0.  Causing a cascading effect that auto-advances through the game.  Issue only occurred the first 2 games.  

Bots not always accepting trades or advancing when real players are ready.  Issue only occurring during some games.  They still seem to allocate resources. Some games they start trading and advancing part of the way through, some they never do.

**Comment by connor4410** [comment]
These issues occurred on chrome for windows.

**Comment by connor4410** [comment]
The bot issues are happening on chrome for android as well.

**Comment by alee** [comment]
These issues should be fixed now, thanks Connor!

**Comment by alee** [comment]
@all-contributors add connor4410 for bug, userTesting
