### ISSUE TITLE
rounds displaying in incorrect order in end game log

### ISSUE THREAD

**Issue by connor4410** [virtualcommons/port-of-mars#517]
This issue is occurring on chrome for android

**Comment by chrstngyn** [comment]
we shouldn't be testing anything less than the iPad resolution - people should be using iPads, laptops, or desktops. we should probably specify that on the login screen

**Comment by connor4410** [comment]
This was using Android on a pad type device.

**Comment by chrstngyn** [comment]
gotcha. i'll change the title of this issue so it's a little more specific. thanks!

**Comment by alee** [comment]
this should be fixed in 3e186be3820b2d269dc42306cfff882654f5d304
