### ISSUE TITLE
consent form and player dashboard responsiveness

### ISSUE THREAD

**Issue by tsommer2** [virtualcommons/port-of-mars#522]
- List of "games played" box/rectangle drops past end of screen in full screen browser mode. Issue is resolved when browser screen is decreased in size. 
- Cannot scroll in full screen browser to "accept" or "decline" consent form. "Accept" and "decline" are visually represented when browser (screen) is decreased in size.

**Comment by tsommer2** [comment]
- Same issues with Chrome

**Comment by chrstngyn** [comment]
resolved in ecd16a4c0b8eb53e3eea1b74d89fa18be78a3455. we can reopen the issue if it becomes relevant again
