### ISSUE TITLE
game reconnection bug: room is locked error

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#529]
Trying to reconnect to the game after being disconnected resulted in a

```
Error: "room "TW6d3I51y" is locked"
```

error

**Comment by cpritcha** [comment]
Removing maxConnections on the gameRoom will help fix the problem. I'll try that.

**Comment by cpritcha** [comment]
Removed maxConnections in 4c7e0b26cb489c2d292a51ca3d6312b50cf42a7f

**Comment by alee** [comment]
closing for now, reopen if this occurs again in playtesting / stress testing
