### ISSUE TITLE
room reconnection troubleshooting and questions

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#540]
currently a game room has as unbounded number of connections allowed. In the lobby rooms users are split into groups of five and sent to a particular game instance. When a game is constructed its short hash and state are saved in the DB. When a player encountered connection problems they are supposed to be able to refresh to get back into the game. Since the credentials are stored in a cookie refreshing does not delete them so they user requests access to their first currently running game instance. Sometimes this fails. 

- Why does it fail and how do we fix it?
- Are the old connections getting garbage collected (how do we test)?
- How do we make it more robust?
- How can we integration test flakey connections?

**Comment by alee** [comment]
add a periodic client ping to the server so the websocket connection won't get closed due to inactivity

**Comment by alee** [comment]
adjust haproxy timeouts as well

**Comment by alee** [comment]
room reconnection appears to be fairly robust now, we've had several disconnections and players able to resume. 

we may need to revisit this on upgrade to colyseus 0.14 / 1.0 though
