### ISSUE TITLE
trade improvements

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#542]
- [x] Make available accomplishments the default when opening the request trade dialog
- [x] See if we can include the costs in the top left pane's accomplishment cards
- [x] #508 
- [x] make trade selection phased so you have to select a person to trade with first, then the amounts you want to trade

**Comment by chrstngyn** [comment]
~- [x] Make available accomplishments the default when opening the request trade dialog~ **fixed 3bc03f872a5557f20a9aa751b3d5a50c30ef51ee**
~- [x] See if we can include the costs in the top left pane's accomplishment cards~ **fixed 089afc1ddd7643cd783e5883d2b48ee6fd56690d**
- [ ] #508 
- [ ] make trade selection phased so you have to select a person to trade with first, then the amounts you want to trade

**Comment by chrstngyn** [comment]
~- [x] #508~ **fixed ** d3ca0aed40f6fd9453844a6646c7b5bb8b306ffd

**Comment by chrstngyn** [comment]
~- [ ] make trade selection phased so you have to select a person to trade with first, then the amounts you want to trade~ **mostly fixed 32840ce8b93805a71d3d7ef716544cd9db7bf2bf**

need better visual cues
- [ ] tooltips on components
- [ ] implement disable button styling on send trade button unless trade is valid

**Comment by chrstngyn** [comment]
instead of tooltips, generate toast ca5fc8c166479250945c832f1b6bd9f541c7a1ba
