### ISSUE TITLE
round introduction

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#547]
includes a

- [x] system health report ( 9cc3c16 )
- [x] add rows for accomplishment system health contributions by role in system health report (e735419)
- [x] player accomplishment purchases
- [ ] completed trades between players

this is managed on server with data structures that are cleared out after exiting every round introduction phase. relevant game events build those data structures up for summary statistics.

**Comment by chrstngyn** [comment]
closing for now

displaying completed trades between players was not implemented but there doesn't seem to be a use for it
