### ISSUE TITLE
events issues

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#549]
### events not permitting interaction

whenever there are multiple events the events skip right through and do not get displayed on the screen with a click through (or zoom by). Seems like it may be an issue with player readiness not getting set properly

- compulsive philanthropy
- bonding through adversity (gain an influence of your choice) was the second event but did not permit interaction
- audit event
- personal gain

### event not showing up in mars log

- [x] difficult conditions did not show up in Mars Log (3rd event)

**Comment by alee** [comment]
Lance as Politician didn't appear to receive the requested resource (though others in the group did..)

**Comment by cpritcha** [comment]
0853cb3b5b69aa2beb6045239956a47377dcb780 added a player readiness reset upon entering the event phase.
