### ISSUE TITLE
system health report: make group contributions calculation clearer

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#551]
need to distinguish when screw cards are used vs group contributions. the current table for system health reports makes it unclear to understand that screw cards have been used. 

change group contributions to net contributions
perhaps add a row to calculate amount of system health deducted as a result of screw cards

**Comment by chrstngyn** [comment]
more specifically, we could break down how each player's purchases of screw cards affected system health

**Comment by MarcoAJanssen** [comment]
An example could be
Prior System Health             80
Group Contributions            35
Events                                  -20
Buying Accomplishments.  -13
Wear and Tear.                    -25
Upcoming System Health.   57

**Comment by alee** [comment]
this is mostly done, but we should improve the table column headers at some point
