### ISSUE TITLE
Compulsive Philanthropy

### ISSUE THREAD

**Issue by MarcoAJanssen** [virtualcommons/port-of-mars#572]
Looking at the data from the last play test, it seems compulsive philanthropy is not working correctly. Perhaps since no votes were counted. What should happen is that the person elected will invest the maximum amount if time blocks into upkeep and cannot change this. I still see that all 5 players make their own choice in investment in upkeep.

**Comment by alee** [comment]
closing, this was likely related to the bug where events were getting skipped.
