### ISSUE TITLE
Make investment location dynamically shift with cost

### ISSUE THREAD

**Issue by Nick42791** [virtualcommons/port-of-mars#58]
Currently, the investments are oriented in a static way, once they are rendered. It might be nice to reorient them if a shift in costs comes up. Alternatively, it could be weird to player to have the investments suddenly shift on the screen.

**Comment by lfaivre** [comment]
costs should only change during an event (correct me if i'm wrong), so there should be no visible switches while a player is investing. going to close this for now.
