### ISSUE TITLE
Login / Registration Workflow Omnibus

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#582]
Dashboard Page

- be able to log out from dashboard page
- registering your email show a toast on the dashboard that an email has been sent. 
- redirect to dashboard works and shows toast message that email has been verified but dashboard still displays action items for verifying your email and consenting to the experiment

TODOs:

- [x] prior to email registration
  1. display email verification page if not verified
  2. display consent form is verified but has not consented
- [x] after email registration and consent we should
  1. display tutorial page
- [ ] after tutorial + quiz has been completed we should 
  1. display an intro survey link on dashboard if not complete (whole page)
  2. display a link to the lobby and a schedule if they've completed the survey and can participate
  3. display a link to the exit survey on dashboard (optional) if they've completed a game this round
  4. display a consoling message if they've been eliminated
  5. display a next round schedule if they've completed all steps for a round and there is a next round
  6. display a victory message if they won the tournament

**Comment by alee** [comment]
initial onboarding still needs some work:

1. after brand new login we should go to consent form
2. after granting consent and submitting email address, send an email verification to user and go to email verification status page that tells them which email address an email was sent to and an option to update that email address or resend the email verification
3. after verified=true, display tutorial and continue as usual

**Comment by alee** [comment]
this has mostly been implemented, need to refine various parts but do so in smaller issues
