### ISSUE TITLE
accomplishment cards show resources from pending investments instead of inventory

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#587]
there's a few issues here and some associated code cleanup to be done on the server side:

Accomplishment cards highlight the resources that you have. This has been inconsistent at times though and there's a larger scale refactoring cleanup pass we should do to fix this:

1. `server/src/rooms/game/events/index.ts` should be performing player state resets and round cleanup / initialization more consistently. Currently various resets have been scattered around various Entered/Exited Phase commands - the semantics here need to be made more clear and consistent.
2. on the client side, the UI should be looking at the player's inventory, not their pending investments to display which resources they have available (could be multiple issues here)
3. somehow, the `player.pendingInvestments.reset()` in the EnteredPurchasePhase and ExitedInvestmentsPhase is not taking effect on the client side

**Comment by chrstngyn** [comment]
fixed 3e6a6db16f7f3ebcc3bb687220e9d0d2029d182c
