### ISSUE TITLE
pending investment not getting cleared properly

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#592]
if 'ready to advance' isn't clicked and player has allocated investments, pending investments are highlighted in accomplishments but inventory amount is correct.

possible causes:
- pending investments aren't getting cleared until EnteredInvestmentPhase
- could be an error on AccomplishmentCard.vue (refactoring in progress on ui branch)

**Comment by alee** [comment]
also occurring on the Purchase Accomplishment phase - after purchasing an accomplishment the resources were correctly removed from the inventory but still highlighted on another accomplishment card.
