### ISSUE TITLE
safari: content security policy

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#593]
the dashboard is shown but Lance was unable to play the game due to content security policy issues: this is likely due to the devtool plugin again, needs additional testing

**Comment by cpritcha** [comment]
https://webpack.js.org/guides/csp/

**Comment by alee** [comment]
safari is unable to join the lobby, returns with an error message `This operation is insecure.`

**Comment by alee** [comment]
tested on latest safari on ios 17 and macos 16 seems fine
