### ISSUE TITLE
tutorial: UI improvements omnibus

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#606]
- [ ] fix #604 
- [x] change CSS for active / purchased accomplishments and distinguish it from the gray Inventory / Accomplishments bars. Right now they look too similar and it's not clear what tab is active
- [x] highlight the HUDLeft buttons that trigger the change in information as well as the information pane themselves (e.g., clicking on the top left briefcase icon brings up the Influence Resources Inventory but we should highlight the top left briefcase icon as well
- [x] add example Mars Log state transform to the Mars Log intro section

**Comment by chrstngyn** [comment]
- [ ] click more info to expand accomplishment card doesn't display any accomplishment info
