### ISSUE TITLE
create branch diagram for tournament round messaging

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#617]
circulate with the rest of the group when done

round 1: hasn't participated, has participated

round 2+: has an active invite, no active invite (has participated in previous rounds, has not participated at all)

**Comment by chrstngyn** [comment]
started creating a diagram

![tournament_message_diagram](https://user-images.githubusercontent.com/8737685/96030822-5cdaad00-0e11-11eb-822e-22749e445413.jpg)

**Comment by alee** [comment]
Added to wiki, thanks!
