### ISSUE TITLE
push settings into redis

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#620]
on server startup we can put the settings into redis and then all lookups go through redis instead. 

if the key is not found in redis, load the data back

then we can modify settings dynamically by mutating the values in redis which would be useful for things like `maxConnections`

**Comment by cpritcha** [comment]
I'll create a settings file that will be loaded into redis on start. Whenever the lobby is entered the `maxConnection` setting from redis is retrieved. You will be able update the settings with the cli (the cli will update the redis cache).

**Comment by cpritcha** [comment]
fixed in 3c29fc7
