### ISSUE TITLE
discard accomplishment shows "Discard Purchased Accomplishment"

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#626]
After an Efforts Wasted event the Discard phase shows discardable accomplishment cards with "Discard Purchased Accomplishment" text instead of just "Discard Accomplishment".

Clicking on this button also does nothing - it appears we are unable to discard those accomplishments.

In the following round the component gets reset and it appears correctly, and discard works again.

![image](https://user-images.githubusercontent.com/22534/96637115-18e51d80-12d3-11eb-9c33-c50ec22f7198.png)

**Comment by chrstngyn** [comment]
reverting the changes as a quick fix before the scheduled games, but will work on a better fix

**Comment by cpritcha** [comment]
in the future we should refactor the calling vue components so that they pass in the appropriate text instead and the text display logic is handled locally by the mars event and discard components,
