### ISSUE TITLE
create new onboarding branch for email signups

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#648]
we should have a separate onboarding branch that collects email signups outside of a scheduled tournament

feature toggle in settings (dynamic settings in redis and settings.ts) that dynamically replaces the existing

`Sign in via ASU CAS` -> `consent form` -> `tutorial` -> `take intro survey`

with 

`Sign up for the next experiment` -> `consent form` -> `Thanks for your interest page with more info`

**Comment by cpritcha** [comment]
we could determine whether to redirect to the tutorial or consent form based on a `isSignUp` field on the User table.

**Comment by alee** [comment]
I'm more in favor of a dynamic variable / setting loaded from settings.json and looked up in redis like the max user connections as it seems more straightforward and easier to switch on/off. Can you describe why you think an extra field in the User table would be preferable?

**Comment by cpritcha** [comment]
Having a field on the User table would allow people to sign up to future tournaments while one is ongoing. The dynamic variable should be easier though and we can always add that ability later if it's needed.

**Comment by alee** [comment]
When a tournament is ongoing, people can still sign up and join as long as it's round 1, if round 2 or later they'd get something similar to this feature toggle but likely the same "sorry you can't join this tournament round as you didn't succeed in round 1 which is now over" message should work there.

**Comment by alee** [comment]
resolved in #651
