### ISSUE TITLE
audit investment log needs to include influence costs

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#659]
We need to multiply the units by the influence costs

For example says things like 

`Researcher has invested 1 time block in Science; 8 time blocks in System Health` instead of invested 2 time blocks

**Comment by chrstngyn** [comment]
maybe we could omit "has invested x timeblocks" to reduce wordiness? focus the log messages more on the amount they will gain vs what they invested. thoughts? @alee @cpritcha 

![image](https://user-images.githubusercontent.com/8737685/108879798-d99b4600-75be-11eb-9e4d-164e9340c227.png)

**Comment by alee** [comment]
I agree we should look for ways to keep the logs as succinct as possible but we should ask the rest of the group. I personally think the time block costs are important since each role has different costs for things and it makes things clear but don't have a great idea for how to display that right now.

Also a minor but important nitpick, it shouldn't say that System Health was added to their inventory.

How about something like

`Politician contributes 3 System Health and adds 2 Government (cost: 4 time), 1 Finance (cost: 3 time) to their inventory.`

?

**Comment by chrstngyn** [comment]
> 
> `Politician contributes 3 System Health and adds 2 Government (cost: 4 time), 1 Finance (cost: 3 time) to their inventory.`
> 

This does read more clearly and communicates the amt of resource they gain and what they actually invested. There isn't a good workaround for formatting these mars log messages (e.g. indenting, new line, etc) at the moment, but reformatting the information in this way is a bit clearer

**Comment by MarcoAJanssen** [comment]
I agree that Allen's description is clear. Can you say 3 time, or do you need to say 3 time blocks?

**Comment by chrstngyn** [comment]
@MarcoAJanssen 3 time or time blocks is fine either way to me. But perhaps to keep the language consistent, we should use "time blocks"
