### ISSUE TITLE
optimize website performance

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#666]
https://developers.google.com/speed/pagespeed/insights/?url=alpha.portofmars.asu.edu%2F&tab=desktop

![image](https://user-images.githubusercontent.com/8737685/109183842-97ebd600-774b-11eb-8106-7e499d91b5f5.png)

**Comment by alee** [comment]
https://expressjs.com/en/advanced/best-practice-performance.html

**Comment by alee** [comment]
we've reduced the background image size to ~450 KB now but chunk vendors is still 2.5MB.. we should vet our client side dependencies carefully and remove unnecessary ones..

**Comment by sgfost** [comment]
closed in favor of #834
