### ISSUE TITLE
increase contrast in system health report

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#675]
`<code>` blocks are too small and dark on dark

1. numbers should be bold off white or brighter color, not dark on dark
2. font size should be same size or larger

add css in NewRound.vue that makes them more readable

also reduce padding between system health report table and text

![image](https://user-images.githubusercontent.com/22534/110181420-ff97c600-7dc8-11eb-8063-37c666d7afaf.png)

**Comment by cpritcha** [comment]
This looks like it's already fixed,
