### ISSUE TITLE
player detail pane display issues

### ISSUE THREAD

**Issue by cpritcha** [virtualcommons/port-of-mars#707]
![image](https://user-images.githubusercontent.com/4530298/130661412-0231e2d9-e4b1-4c58-abba-dfd1052ee062.png)

- not displaying accomplishment costs
- science is rendered to the side (and there is a horizontal scroll bar instead of vertical)

**Comment by alee** [comment]
fixed

TODO: consider moving accomplishments pane up to take the available empty space next to the player avatar since that list is typically longer #759
