### ISSUE TITLE
breakdown of trust: unable to select second influence

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#741]
at today's playtest a player with exactly 2 finance was unable to save both finance. It stopped them at 1, and then when the phase switched over nothing carried over.

1. should lock in whatever the user had selected in pending investments when the phase switches
2. investigate bug likely in the investment card spin button max

**Comment by chrstngyn** [comment]
was able to recreate it locally.

```
get maxInfluenceInvestment() {
    if (this.breakdownOfTrust) {
      console.log(`${this.remainingTimeBlocks} : x : ${this.currentInfluence}`);
      return Math.min(this.remainingTimeBlocks, this.currentInfluence);
    }
    // FIXME: 10 should be pulled from somewhere else, max time blocks in the store?
    return this.cost > this.remainingTimeBlocks ? this.units : this.maxTimeBlocks;
  }
```

The problem may be occurring because when remaining time blocks gets modified to +1, return Math.min takes the min of 1 (remaining time blocks) and 2 (current influence) which sets max influence investment = 1

**Comment by chrstngyn** [comment]
the calculation for max Influence should be

```
  get maxInfluenceInvestment() {
    if (this.breakdownOfTrust) {
      return this.currentInfluence;
    }
    // FIXME: 10 should be pulled from somewhere else, max time blocks in the store?
    return this.cost > this.remainingTimeBlocks ? this.units : this.maxTimeBlocks;
  }

```
