### ISSUE TITLE
create better ux to guide players during gameplay

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#754]
- #761
- add ux elements like timeout hints (e,g. if player is idle for x amount of time, hint to user that they should be purchasing an accomplishment or click ready to advance)

**Comment by chrstngyn** [comment]
should we put a chat in the waiting lobby so players can interact before the game starts?

**Comment by alee** [comment]
waiting lobby now has chat functionality in the rooms

closing in favor of more specific in-game UX work
