### ISSUE TITLE
create in-game manual/cheat sheet

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#761]
in the fall 2021 tournament, players tended to forgo the tutorial which caused confusion in the game. adding a manual or cheat sheet in-game would be useful for players to reference

**Comment by chrstngyn** [comment]
https://github.com/virtualcommons/port-of-mars/wiki/Manual

**Comment by alee** [comment]
fixed in 4147acdae00b62589651908c7d6d482168ca3dab
