### ISSUE TITLE
ways to increase app performance

### ISSUE THREAD

**Issue by chrstngyn** [virtualcommons/port-of-mars#788]
according to Lighthouse Report via Chrome dev tools

Performance: 56/100

- Serve images in [next-gen formats](https://web.dev/uses-webp-images/?utm_source=lighthouse&utm_medium=devtools)
Image formats like WebP and AVIF often provide better compression than PNG or JPEG, which means faster downloads and less data consumption

- Enable text compression
Text-based resources should be served with compression (gzip, deflate or brotli) to minimize total network bytes.

- Reduce unused JavaScript and CSS

**Comment by chrstngyn** [comment]
code splitting method via Discord Engineering Blog
https://blog.discord.com/how-discord-maintains-performance-while-adding-features-28ddaf044333

**Comment by sgfost** [comment]
closed in favor of #834
