### ISSUE TITLE
add social auth

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#790]
https://github.com/auth0/passport-auth0

**Comment by alee** [comment]
Nuxt 3 auth may need to be manually done until the proper auth integration is supported:

https://github.com/nuxt/framework/discussions/3447

See https://javascript.plainenglish.io/nuxt-3-auth0-authentication-70e86a98a3b3 for an example using Nuxt 3 middleware and auth0 which is likely the auth provider we will use.

**Comment by alee** [comment]
JWT pitfalls: https://redis.com/wp-content/uploads/2022/03/jwts-not-safe-e-book.pdf

**Comment by alee** [comment]
https://community.auth0.com/t/auth0-spa-js-vue3-nuxt3-and-a-document-h3-error/87604

**Comment by alee** [comment]
nuxt support on hold due to #809 

looking into implementing passport auth0 strategy:
 
https://auth0.com/blog/auth0-s-express-openid-connect-sdk/

**Comment by alee** [comment]
FB Gaming Login: https://developers.facebook.com/docs/games/acquire/login-for-gaming

**Comment by sgfost** [comment]
google + fb login both added in open beta release
