### ISSUE TITLE
admin stats

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#794]
landing page dashboard + admin page dashboard (with extra curator / management functionality)

1. total number of active games
2. total number of completed games
3. games without bots that survived
4. reported players (admin)
5. active game feeds (admin)

**Comment by chrstngyn** [comment]
consider creating a separate app for admins to view game statistics

**Comment by sgfost** [comment]
example of an admin dashboard for reference: https://github.com/colyseus/colyseus/tree/master/packages/monitor

tentative list of things we may want on the admin page:
- list of game rooms
- game event feed for each
- detail of reported chat message/user 
- ability to ban users and any other similar management commands
- app settings control (i.e. gift card amt, scheduler settings, etc.)?
