### ISSUE TITLE
prep for Commons in Space pretest

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#811]
special casing for the Commons in Space pretest

- full hour launch time between 7-8am Arizona time that allows anyone to sign in and wait in the lobby
- include zoom link details in the lobby page for technical support

**Comment by sgfost** [comment]
In https://github.com/virtualcommons/port-of-mars/pull/815/commits/060dc5d842236a87b2ae03175ef4ec4827242119 I've disabled Facebook signin when in production and added the settings we likely want in [settings.template.json](https://github.com/virtualcommons/port-of-mars/blob/060dc5d842236a87b2ae03175ef4ec4827242119/server/deploy/settings.template.json) for convenience which includes `isAutoSchedulerEnabled = false` so we can avoid any auto-scheduler conflicts/confusion with the main launch time.

And one option for creating the launch time:
`yarn cli schedule create --date "2022-11-04T15:00:00+01:00" --before 15 --after 120`
(lobby open 6:45 - 9:00 AM MST)
