### ISSUE TITLE
compulsive philanthropy mandatory timeblock investment not displaying in SHR for selected philanthropist

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#817]
System Health Report at the beginning of the round following a Compulsive Philanthropist showed 0 investment for the voted "Philanthropist"

**Comment by sgfost** [comment]
Seems like there's more bugs with the system health reporting/calcs. Sometimes incorrectly shows 0 for personal contributions + bad calculations:

![Screenshot from 2022-11-18 10-48-00](https://user-images.githubusercontent.com/46429375/202769859-f9eeb149-af37-4d6b-b434-f4655756b53b.png)

Deserves a more thorough look

related: #772, #755

**Comment by alee** [comment]
![image](https://user-images.githubusercontent.com/22534/202804896-55d77f53-d964-46fd-9b30-2d338950b38c.png)

**Comment by alee** [comment]
working with @sgfost this afternoon to resolve this problem revealed a deep rabbit hole.

the event handling for Compulsive Philanthropy on the server side used to simply add the player's time blocks to System Health directly (which would not work correctly if system health costs were modified, but would be OK if the player's time blocks were modified)

However, during the Invest phase, the Client decides how much investment has occurred and sends back a client investment message (with timeblocks set to 0, and pending investments of 0), which effectively overrides anything that happens server-side later.

The "right" way to solve this is probably to be able to synchronize modifications to pendingInvestments on the server side with the client, and round-trip that data from server -> client -> server. This is arguably more inefficient since there's no need to pass any data back and forth between the server and client in this situation but it prevents inconsistency and

**Comment by alee** [comment]
Synchronizing `pendingInvestments` across the server and client created a lot of bugs on how the client expects to use pendingInvestments locally so we've backtracked from that line of development and are using a sentinel value in Player to indicate that they are the compulsive philanthropist and corner case the Player's investment logic accordingly. 

3167f20452251bfb4ee5a1055f91d7d545023c8b

**Comment by sgfost** [comment]
Client now shows the forced investment and disables buttons. The amounts displayed are still client-side state but the server remains authoritative in terms of what actually gets invested at the end of the phase.

![compphil-ui-fixed](https://user-images.githubusercontent.com/46429375/203636254-b9b9f058-b449-4fb1-88d7-d8f7fcfb4924.png)
