### ISSUE TITLE
system health report not being calculated properly again

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#845]
![image](https://user-images.githubusercontent.com/22534/218203288-0367ea59-9411-4718-8528-b07ffce0ecdd.png)

**Comment by alee** [comment]
from the same game:

![image](https://user-images.githubusercontent.com/22534/218204404-0a55454f-7c01-4aed-b859-e5336b87fcc9.png)

**Comment by sgfost** [comment]
room id: 3ovh1JXoP on staging

**Comment by alee** [comment]
![image](https://user-images.githubusercontent.com/22534/218205372-7368baca-49e3-4e2e-9141-03810f44704a.png)

looks like it's not including my contributions? need to compare with another players

**Comment by alee** [comment]
![image](https://user-images.githubusercontent.com/22534/218206596-3c94b98e-9248-4434-9b6a-93039201b825.png)

**Comment by CharlesSheelam** [comment]
![Screenshot 2023-02-10 145846](https://user-images.githubusercontent.com/100802119/218206847-c394d9c9-cb6f-456e-9ff4-1fcda9cc9b3c.png)

**Comment by manuvanegas** [comment]
Oh I only took the screenshot of the left side

![image](https://user-images.githubusercontent.com/44076078/218206806-37a02d32-5f19-4b61-b3af-7ba5e0a13ddb.png)

**Comment by Tkawamura02** [comment]
![Screen Shot 2023-02-10 at 2 56 54 PM](https://user-images.githubusercontent.com/86638759/218206934-7f247391-b843-424d-a417-b77a3d6be61a.png)
Quick Screenshot of the calculation

**Comment by sgfost** [comment]
start of round 6 of game: SvBkZGzEa
![round6-SvBkZGzEa](https://user-images.githubusercontent.com/46429375/218207026-d0ca9b32-3b1d-4a8c-ad54-07fe15325a5c.png)

**Comment by Krisha100** [comment]
![bug](https://user-images.githubusercontent.com/57967961/218207077-74951e6f-fdf4-4dc9-8d6a-abed1f4ab9f9.png)

**Comment by alee** [comment]
![image](https://user-images.githubusercontent.com/22534/218207932-49eb5ab7-9ac5-4df1-9d09-07cb9189d09d.png)

**Comment by alee** [comment]
![image](https://user-images.githubusercontent.com/22534/218208009-cc644432-7f01-430e-9a46-cb40e25cb7cd.png)

**Comment by CharlesSheelam** [comment]
![1](https://user-images.githubusercontent.com/100802119/218207952-2f8cf342-d983-451c-9af9-8c9fee436007.png)
![2](https://user-images.githubusercontent.com/100802119/218207958-935a3768-2ce6-48f7-a32e-9c69056b0852.png)
 
Invested 10 in system health and confirmed, however health summary screen showed that I invested 0.

**Comment by Krisha100** [comment]
![Screen Shot 2023-02-10 at 3 07 14 PM](https://user-images.githubusercontent.com/57967961/218208043-cb7e57b8-eee6-4cb2-8747-945a57b2377e.png)

**Comment by manuvanegas** [comment]
![image](https://user-images.githubusercontent.com/44076078/218208059-0345e717-662c-45fa-8997-f69cb3428fb2.png)

**Comment by saachibm** [comment]
![Screen Shot 2023-02-10 at 3 06 21 PM](https://user-images.githubusercontent.com/123594505/218208119-2a1c9f10-eeb1-45fb-a5b0-71f0f45ae72c.png)

**Comment by Tkawamura02** [comment]
![Screen Shot 2023-02-10 at 3 06 26 PM](https://user-images.githubusercontent.com/86638759/218208336-33c5edd3-0913-4cf8-bb38-2095bad5cbeb.png)

**Comment by sgfost** [comment]
The issue lies in updating group contributions on the client: https://github.com/virtualcommons/port-of-mars/blob/2ad6dfb0d17236ffc49952c4ffe1819764909c32/client/src/api/game/response.ts#L152-L154

For some unknown reason, sometimes it gets incorrectly set to 0 for one player which leads to the total contributions being off by however much the real investment was.

**Comment by alee** [comment]
closing for now, re-open if we encounter this in pretesting this month
