### ISSUE TITLE
create leaderboard page view

### ISSUE THREAD

**Issue by sgfost** [virtualcommons/port-of-mars#852]
Create a new page in `client/src/views` that will display a tabular leaderboard/scoreboard as well as a player's personal stats if they are signed in (in a separate tab-style view)

#### Specifications
- use bootstrap-vue components such as `b-table`, etc. https://bootstrap-vue.org/docs
- use consistent styling (examples of pages with tables can be found in admin dashboard)
- consider responsiveness for different screen sizes in the page layout
- use data retrieved from the server side API #851
  - create a `LeaderboardAPI` in `client/src/api` to handle the requests with AJAX for the vue component
  - does not need to be 'real time', fetching the data once will be enough
  - should be able to choose between seeing the data for bot and non-bot games (5 human players)
- global leaderboard should be viewable without authentication at the route `/leaderboard/global`, `/leaderboard` should redirect here
- personal stats should be at `/leaderboard/stats` and should only be accessible by authenticated users
  - navigation tabs: https://bootstrap-vue.org/docs/components/nav#tab-style
  - router setup: https://github.com/virtualcommons/port-of-mars/blob/main/client/src/router.ts
  - old player stat component: https://github.com/virtualcommons/port-of-mars/blob/main/client/src/components/leaderboard/PlayerStatItem.vue

_use this issue for discussion/planning_

**Comment by Tkawamura02** [comment]
Saachi and I worked on the b-table addition to Leaderboard.vue on her branch! We zoomed on Sunday and worked on it together

**Comment by sgfost** [comment]
excellent, now that there's some changes we can open it as a PR so its easier to track/make review comments

**Comment by Tkawamura02** [comment]
Saachi and I worked on Leaderboard.vue (b-button and format) and created Leaderboard.ts (Leaderboard API and tried to handle request with AJAX)

**Comment by sgfost** [comment]
sounds good, we'll probably want to do that in `created()` as well but a refresh button is good and has precedent elsewhere. @saachibm @Tkawamura02 will you two be around this Friday? If so, we can use that time to work on the backend portion/anything else

**Comment by Tkawamura02** [comment]
I can definitely be there! I will try to make it to the meeting in-person :)

**Comment by saachibm** [comment]
I should be able to join through Zoom from 2-4pm!

**Comment by sgfost** [comment]
Good progress on the page in db73e43, what remains is actually using the data in the table with the ability to switch between bot/botless highscores

Additionally, we should get some use out of the personal stats that we are already computing (will require some changes to work across tournament rounds) by integrating this into the page somehow, perhaps a similar setup to the admin dash where leaderboard and personal stats are two sub tabs under the same top-level route.
Note: there is also a component for this as well but could use some updating.

**Comment by Tkawamura02** [comment]
1. fix any corner cases / bugs in the query logic that are causing the current leaderboard issues with the null points
2. Ensure that the only games ending in success count in the points total for a given player
3. Embed a short summary leaderboard view in the landing page as a contrasting section (after Gameplay?). This would only include the top 10 players and could be parameterizable Prop for the component
4. Minor styling improvements as needed
