### ISSUE TITLE
Postgres not starting up fully resulting in server crash

### ISSUE THREAD

**Issue by sgfost** [virtualcommons/port-of-mars#864]
Getting "FATAL: the database system is starting up" from postgres after `wait-for-it.sh` finds that the port is available. We may need to check https://www.postgresql.org/docs/current/app-pg-isready.html as well

**Comment by alee** [comment]
Ah, this keeps happening on docker-ce upgrades, when the docker daemon restarts. System reboots seem to not cause this but we should definitely switch to pg-isready for all of our apps - looks like a straightforward replacement

https://stackoverflow.com/questions/46516584/docker-check-if-postgres-is-ready
