### ISSUE TITLE
add server healthcheck

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#876]
Applying system upgrades to docker-ce restarts the docker daemon and all running containers. Normally this isn't an issue but for some reason the db <-> server container healthcheck does not register properly and the server dies with a basic db not ready message:

```
port-of-mars-server-1  | [06:56:19.691] FATAL (30): the database system is starting up
port-of-mars-server-1  |     filename: "/code/server/src/index.js"
port-of-mars-server-1  |     err: {                                                                                
port-of-mars-server-1  |       "type": "DatabaseError",
port-of-mars-server-1  |       "message": "the database system is starting up",
port-of-mars-server-1  |       "stack":   
port-of-mars-server-1  |           error: the database system is starting up
port-of-mars-server-1  |               at Parser.parseErrorMessage (/code/server/node_modules/pg-protocol/dist/parser.js:287:98)
port-of-mars-server-1  |               at Parser.handlePacket (/code/server/node_modules/pg-protocol/dist/parser.js:126:29)
port-of-mars-server-1  |               at Parser.parse (/code/server/node_modules/pg-protocol/dist/parser.js:39:38) 
port-of-mars-server-1  |               at Socket.<anonymous> (/code/server/node_modules/pg-protocol/dist/index.js:11:42)
port-of-mars-server-1  |               at Socket.emit (node:events:513:28)
port-of-mars-server-1  |               at Socket.emit (node:domain:489:12)
port-of-mars-server-1  |               at addChunk (node:internal/streams/readable:315:12)
port-of-mars-server-1  |               at readableAddChunk (node:internal/streams/readable:289:9)
port-of-mars-server-1  |               at Socket.Readable.push (node:internal/streams/readable:228:10)
port-of-mars-server-1  |               at TCP.onStreamRead (node:internal/stream_base_commons:190:23)         
port-of-mars-server-1  |       "length": 104,           
port-of-mars-server-1  |       "name": "error",
port-of-mars-server-1  |       "severity": "FATAL",
port-of-mars-server-1  |       "code": "57P03",                                                                    
port-of-mars-server-1  |       "file": "postmaster.c", 
port-of-mars-server-1  |       "line": "2329",
port-of-mars-server-1  |       "routine": "ProcessStartupPacket"
port-of-mars-server-1  |     }                  
```

Not sure why the containers aren't respecting their docker compose configuration when restarted but should investigate a bit more on staging. In the meantime, automated upgrades to production have been disabled so whenever we upgrade docker on the machine we'll need to manually double check that the services are up.

**Comment by sgfost** [comment]
I think the problem is that docker compose doesn't have any involvement in the restart after docker itself goes down. Might need to handle the failed connection at the app level

**Comment by alee** [comment]
Yeah, it seems like it just attempts a blind restart. Not sure why this is only affecting pom and not any of our other apps though..

**Comment by sgfost** [comment]
May be that they already have some way of handling that?

#877 adds some handling for a failed connection which seems to do the trick locally. I'll try to replicate the exact problem on staging to make sure

**Comment by sgfost** [comment]
Can't manage to replicate the exact sequence of events on staging but my crude approximation (delaying the db startup while the server keeps trying to connect) still works
