### ISSUE TITLE
Meta/FB login appears to be broken

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#886]

**Comment by sgfost** [comment]
Hard to tell whether something broke which prompted FB to alert us or something got disabled along the way on their end.. FB auth seems like far more trouble than its worth but I wouldn't want to leave no alternative to google, not that FB is a particularly good one. Maybe revisit email-based OTP auth in preparation for a tournament?

**Comment by alee** [comment]
fixed, was a set of misconfigured client / app secrets
