### ISSUE TITLE
integrate "Events this round" and "All events" widgets

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#888]
Consider integrating the "Events This Round" display into the "All Events" widget

- Rename to "Events"
- visually highlight the events received this round in the "Events" widget and scroll to them automatically (if full event deck is being shown or there is a history of past events)

**Comment by sgfost** [comment]
Need to add some extra metadata to events (server side) so the client can know which cards in the deck are active. Round events should stay in the case that the deck is not available. 

Also need to give the client the event ids (unique db ids) to get access to transitions, etc.
