### ISSUE TITLE
identify mars events that require special case client handling

### ISSUE THREAD

**Issue by alee** [virtualcommons/port-of-mars#99]
- Breakdown of Trust: `PICK_INFLUENCES` keep up to 2 influence resource (units, not types)
- Changing Tides: `PICK_ACCOMPLISHMENT_CARD` discard all currently available accomplishment cards and draw 1 new (they get 3 at the end of the round again)
- Personal Gain: `YES_NO_VOTE` Each player secretly chooses Yes or No. Then, simultaneously, players reveal their choice. Players who chose yes gain 6 extra Time Blocks this round, but destroy 6 Upkeep
- Bonding through Adversity: `PICK_INFLUENCES` (special case) Each player gains one Influence of their choice.
- Compulsive Philanthropy: `VOTE_FOR_PLAYER` Players must vote for one player to put all their Time Blocks into Upkeep this round.
- Hero or Pariah: `VOTE_FOR_PLAYER` CHOOSE ONE  Players must vote for 1 player to lose all Influence Players must vote for 1 player to gain 4 of their specialty Influence
- Audit: `NO_PANTS` For the next round, players play with dividers down. (Players can see how each other player allocates their time.) _this text needs adjustment_
- Efforts Wasted: `PICK_ACCOMPLISHMENT_CARD` Each player must discard an Accomplishment they purchased.
- Markets Closed: `DISABLE_TRADING` No trading allowed
- Stymied: `NO_SPECIALTY_INFLUENCE` Players may not earn their specialty Influence this round. (Culture for Curator, Business for Entrepreneur, Government for Politician, Science for Researcher, Legacy for Pioneer) 
- Solar Flare: `DISABLE_TRADING & NO_CHAT` Destroy 5 Upkeep. Skip the discussion and trading phases this turn. (Players may not discuss how they allocate their time and may not trade Influences.)
- Interdisciplinary: `ENABLE_ALL_INVESTMENTS` For this round, each player can spend 3 Time Blocks to earn an Influence in either of the 2 Influences they normally can't create.
- Out of Commission: `ROLE_HAS_3_TIME_BLOCKS` The <Role> only receives 3 time blocks 
- `UPKEEP_DESTRUCTION` (various events destroy upkeep, this should probably be visually marked)

**Comment by lfaivre** [comment]
This has been implemented and is being integrated with the server in phases.
